jwiegley/gitlib

git-monitor/Main.hs
gitlib-libgit2/Git/Libgit2.hs
gitlib-libgit2/gitlib-libgit2.cabal

Another time issue, just like with `logging`, and one change in FFI's `calloc` avaiability.
I have tested these with 7.10 under nixos, but not older versions---they seem pretty straightforward (and I'm starting to feel all too comfortable with making these sorts of changes), but might be worth your time to double check.

Three bits of unfortunate conditional noise

---

hlibgit2/Setup.hs
hlibgit2/hlibgit2.cabal

This is based on the change in jgm/zip-archive#22 which was solving a similar issue---having cabal truly depend on an external tool.
Incidentally, `cabal2nix` now recognizes these dependencies and puts them in its generated expression; if you want, I'm happy to apply this change to gitlib-cmdline as well.

Make git a test dependency of hlibgit2.

---

gitlib-cmdline/Setup.hs
gitlib-cmdline/gitlib-cmdline.cabal

Do it at the cabal level, so the nix expressions can easily be
regenerated without fixups.

Make git a test dependency of gitlib-cmdline.

---

gitlib/Git/Tree/Working.hs
gitlib/gitlib.cabal
hlibgit2/Bindings/Libgit2/Windows.hsc
hlibgit2/hlibgit2.cabal

This patch improves Windows compatibility of this library. It's basically the same as https://github.com/jwiegley/gitlib/issues/50 .
I also faced to [stack(or hsc2hs)'s bug](https://github.com/commercialhaskell/stack/issues/1540#issuecomment-170185997). I had to use following workaround:
```
$ touch hlibgit2/BindingsLibgit2Windows.hsc
```

Improve Windows compatibility

---

hlibgit2/hlibgit2.cabal

Added paths for OS X Homebrew installation of `openssl`

---

gitlib-libgit2/Git/Libgit2.hs

Return the commit objects behind annotated tags instead of asserting.

Git/Libgit2.hs: pass-through of annotated tags

---

gitlib/Git/Working.hs

This seems to fix the missing `MonadBaseControl` error.
Fixes #72

Fix missing MonadBaseControl

---

gitlib/Git/Blob.hs
gitlib/Git/Commit.hs
gitlib/Git/Object.hs
gitlib/Git/Reference.hs
gitlib/Git/Tree.hs
gitlib/Git/Types.hs
gitlib/Git/Working.hs
gitlib/gitlib.cabal

Some type synonyms (`Producer`, `Source`, etc.) and some functions (`$$`, `$=`, etc.) were deprecated, and [`.|`](https://hackage.haskell.org/package/conduit-1.3.0.2/docs/Data-Conduit.html#v:.-124-) was introduced in conduit-1.2.8.

Avoid using deprecated conduit functions

---

git-monitor/git-monitor.cabal
gitlib-cmdline/gitlib-cmdline.cabal
gitlib-libgit2/Git/Libgit2.hs
gitlib-libgit2/Git/Libgit2/Internal.hs
gitlib-libgit2/Git/Libgit2/Types.hs
gitlib-libgit2/gitlib-libgit2.cabal
gitlib-test/Git/Smoke.hs
gitlib-test/gitlib-test.cabal
gitlib/Git/Commit/Push.hs
gitlib/Git/Repository.hs
gitlib/Git/Tree/Working.hs
gitlib/Git/Types.hs
gitlib/Git/Working.hs
gitlib/gitlib.cabal

Hi! Thanks for the great libraries.
Due to changes in the conduit/resourcet ecosystem, a lot of things now no longer work with monad-control/MonadBaseControl functions (some instances have appeared to disappear from those libraries), so I've tried my best to see if it makes sense to move the entire library to unliftio/MonadUnliftIO style.  Things seem to have been pretty straightforward!
Let me know if this isn't the direction you want to go, or if there's anything I can touch up!

Migrate to unliftio, away from monad-control

---

gitlib/README.md

I've had a go at updating the gitlib tutorial. I'm no expert, but this version does create a commit with a new file on top of an existing HEAD.
Feedback welcome. I can make any changes and re-test if you're strapped for time.
Should fix #81 if it were promoted to proper Haskell source code!

Update README tutorial so that it works.

---

gitlib-cmdline/Setup.hs
gitlib-cmdline/gitlib-cmdline.cabal
hlibgit2/Setup.hs
hlibgit2/hlibgit2.cabal

As mentioned [here](https://github.com/jwiegley/gitlib/commit/bd26e038aca158e19af32340ec8a58bc7b13dda3#commitcomment-33953077), custom Setup.hs files cause problems for cabal v2-build.
The build-tools stanzas are also deprecated but don't seem to be causing any problems right now, so I've left them alone.
This partially reverts commit 76d8be594abf1341561ed212736c5e28dd940708
and commit bd26e038aca158e19af32340ec8a58bc7b13dda3.
("Make git a test dependency of gitlib-cmdline."
and "Make git a test dependency of hlibgit2.")
The downside of this change is that if git is missing it will no
longer be flagged by cabal.

Get rid of custom Setup.hs files

---

gitlib/Git/Types.hs
gitlib/gitlib.cabal

The current code uses `fail` in the context of the typeclass `Monad`, while it is actually defined in `MonadFail`. I ran into this issue while attempting to build with latest versions of base etc.

Fix constraint mismatch

---

gitlib/Git/Types.hs

Compiling generates these warnings:
```
Git/Types.hs:42:19: warning: [-Wstar-is-type]
Using ‘*’ (or its Unicode variant) to mean ‘Data.Kind.Type’
relies on the StarIsType extension, which will become
deprecated in the future.
Suggested fix: use ‘Type’ from ‘Data.Kind’ instead.
|
42 |     type Oid r :: *
|                   ^
```
This change follows its advice to use `Type` instead of relying on the
StarIsType extension.

Use Data.Kind.Type instead of asterisk

---

.gitignore

These are created in the case where gitlib is compiled as a sub-project
of an unrelated project that uses stack rather than cabal.

git-ignored .stack-works folders generated by stack

---

gitlib-libgit2/Git/Libgit2.hs
gitlib/Git/Types.hs

This adds a method to gitlib to perform diffs between trees. The data
types that are intended to be created by the method are general and
cover most bases for the `git_diff_tree_to_tree` function. An
implemention is added to gitlib-libgit2.
Closes #71

Add support for git_diff_tree_to_tree

---

hlibgit2/hlibgit2.cabal

Apparently gcc 8.3 at least now makes it an error to disable -Wformat but not -Wformat-security, otherwise we get:
error: -Wformat-security ignored without -Wformat [-Werror=format-security]

uptime hlibgit2 to compile with newer gcc

---

hlibgit2/hlibgit2.cabal

Without the `-Wno-format-security` flag, GCC 7 fails with this error:
```
cc1: error: -Wformat-security ignored without -Wformat [-Werror=format-security]
```

Fix flag issue with GCC 7.

---

gitlib-cmdline/Git/CmdLine.hs
gitlib-hit/Git/Hit.hs
gitlib-libgit2/Git/Libgit2.hs

Fixes conduit related compile errors e.g.:
```
gitlib-libgit2>       Expected: Maybe (Git.CommitOid LgRepo)
gitlib-libgit2>                 -> Git.CommitOid LgRepo
gitlib-libgit2>                 -> Bool
gitlib-libgit2>                 -> ConduitT i (Git.ObjectOid LgRepo) m ()
gitlib-libgit2>         Actual: Maybe CommitOid
gitlib-libgit2>                 -> CommitOid -> Bool -> Producer m0 ObjectOid
gitlib-libgit2>     • In the expression: lgSourceObjects
gitlib-libgit2>       In an equation for ‘Git.sourceObjects’:
gitlib-libgit2>           Git.sourceObjects = lgSourceObjects
gitlib-libgit2>       In the instance declaration for ‘Git.MonadGit LgRepo m’
gitlib-libgit2>     • Relevant bindings include
gitlib-libgit2>         sourceObjects :: Maybe (Git.CommitOid LgRepo)
gitlib-libgit2> …
```

re conduit deprecations: use ConduitT directly

---

gitlib/gitlib.cabal

This fixes compilation errors, and compilation works with the update.

Bump base16-bytestring major version

---

gitlib-cmdline/Git/CmdLine.hs
gitlib-cmdline/gitlib-cmdline.cabal
gitlib-hit/Git/Hit.hs
gitlib-hit/gitlib-hit.cabal
gitlib-libgit2/Git/Libgit2.hs
gitlib-libgit2/gitlib-libgit2.cabal
gitlib-test/Git/Smoke.hs
gitlib-test/gitlib-test.cabal
gitlib/Git/Blob.hs
gitlib/Git/Object.hs
gitlib/Git/Tree.hs
gitlib/Git/Types.hs
gitlib/Git/Working.hs
gitlib/gitlib.cabal

This PR addresses https://github.com/jwiegley/gitlib/issues/64 by adding a `recursive::Bool` argument to the user-interface function `listTreeEntries` and to the library-backend interface function `sourceTreeEntries` and modulating the `git_tree_walk` callback to return `0` when a recursive traversal is required or return `1` when only immediate children are desired. In this way, `listTreeEntries` can be used for either walking the whole repo or listing a single tree object's immediate members. Unfortunately, it is a breaking change.
* ~~git-monitor~~ (does not call the changed functions; already compiles with no changes)
* ~~hlibgit2~~ (does not depend on `gitlib`)

Change listTreeEntries and sourceTreeEntries to take a recursive::Bool argument
